### ISSUE TITLE
Harmonising common Kubernetes parameters across components 

### ISSUE THREAD

**Issue by oginskis** [agilestacks/kubeflow-components#37]
Let's introduce common of parameters of the components that deploy to Kubernetes:

```
parameters:
- name: kubernetes
  parameters: 
  - name: namespace
  - name: serviceAccount
```
and use `component` discriminator in `params.yaml` to distinguish between components (if needed), for example:

```
- name: kubernetes
  parameters:
  - name: namespace
    value: kube-ingress

- name: kubernetes
  component: cert-manager
  - name: serviceAccount
    value: cert-dns-manager

- name: kubernetes
  component: external-dns
  parameters:
  - name: serviceAccount
    value: ext-dns-manager
```
 In the example above we deploy both `cert-manager` and `external-dns` to the same namespace, but they use different service accounts.

Currently let's use this approach to `nginx`, `cert-manager` and `external-dns`, but later extend it to other Kubernetes components!
