### ISSUE TITLE
Use key-value pairs for istio-ingressgateway 

### ISSUE THREAD

**Issue by akranga** [agilestacks/kubeflow-components#52]
Istio `Gateway` resource binds to the `istio-ingressageway` by labels. Today we are hard-coding labels to:

```yaml
labels:
  app: "${hub.coponentName}"
  istio: "${hub.coponentName}" 
```

This makes it inflexible for configuration. Components, such as `kubeflow-common` or `knative-serving` (these component integrate with IngessGateway) expects that  every istio ingress gateway would have these labels, which not always true. There is a proposition to restructure parameters to allow user to define any labels they want. Proposing the following structure

```yaml
parameters:
- name: kubernetes.labels
  value:
    app: ingressgateway
    istio: ingressgateway
```

Then values can be picked up as a `gotemplate` as the following

```yaml
# helm config
labels: 
{{- range $key, $value := .kubernetes.labels }}
  {{$key}}: {{$value}}
{{- end}}
```

Then it should generate something like

```yaml
labels:
  app: ingressgateway
  istio: ingressgateway
```

Yet now these are now configurable labels.

## Limitations

* `hubctl` doesn't support interpolation for map types
* You cannot use this as component output

**Comment by akranga** [comment]
Side note: it looks like we would need to move other under `kubernetes` namespace. This will make it consistent

```yaml
parameters:
- name: kubernetes.namespace
- name: kubernetes.replicas
- name: kubernetes.serviceType
```

**Comment by akranga** [comment]
Similar to labels adding `kubernetes.requests` and `kubernetes.limits`

**Comment by akranga** [comment]
Discussed with @TheRealSpaceShip separately. To use approach similar to `ingress.hosts` that will look like the following;

```yaml
parameters:
      - name: kubernetes.labels
        value: >-
          istio=ingressgateway
          app=ingressgateway
```

Then the user can use `gotemplates` to parse these files like:

```yaml
labels: 
{{- range .kubernetes.labels | splitList " "}}
  {{. | replace "=" ": "}}
{{- end}}
```

or 

```yaml
labels: 
{{- range .kubernetes.labels | splitList " "}}
  {$key := . | splitList "=" | first -}}
  {$value := . | splitList "=" | last -}}
  {{$key}}: "{{$value}}"
{{- end}}
```

Rationale: today `hubctl` has limitations that will be confusing for the user.

1. Maps doesn't support string interpolations
2. `hubctl` will render map that contains key `name` differently 
3. User can accidentally change type to string without knowing it
